server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seven?characterEncoding=utf-8&useSSL=false
    username: root  
    password: root 
    minIdle: 1  
    maxActive: 2  
    initialSize: 1  
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT '1' 
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    content-type: text/html 